name: window_manager_workspace
repository: https://github.com/leanflutter/window_manager

packages:
  - examples/**
  - packages/**

command:
  bootstrap:
    # Uses the pubspec_overrides.yaml instead of having Melos modifying the lock file.
    usePubspecOverrides: true

scripts:
  analyze:
    exec: flutter analyze --fatal-infos
    description: Run `flutter analyze` for all packages.

  test:
    exec: flutter test
    description: Run `flutter test` for a specific package.
    packageFilters:
      dirExists:
        - test

  format:
    exec: dart format .
    description: Run `dart format` for all packages.

  format-check:
    exec: dart format . --set-exit-if-changed
    description: Run `dart format` checks for all packages.

  fix:
    exec: dart fix . --apply
    description: Run `dart fix` for all packages.
